version: '2'
services:
  flyway:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes_from:
      - sample
  sample:
    image: tianon/true
    volumes:
      - ./sample/sql:/opt/flyway/sql
      - ./sample/conf:/opt/flyway/conf

